export const COUNTRIES = ["United States","Canada","United Kingdom","Ireland","Australia","New Zealand","Germany","France","Spain","Italy","Portugal","Netherlands","Belgium","Switzerland","Austria","Sweden","Norway","Denmark","Finland","Iceland","Poland","Czech Republic","Greece","Turkey","Russia","Ukraine","Japan","South Korea","China","India","Singapore","Thailand","Vietnam","Indonesia","Malaysia","Philippines","Mexico","Brazil","Argentina","Chile","Colombia","Peru","South Africa","Egypt","United Arab Emirates","Israel","Saudi Arabia","Nigeria","Kenya","Morocco","Other"];

export const CITY_DATA = {
  "United States": ["New York, NY","Los Angeles, CA","Chicago, IL","Houston, TX","Phoenix, AZ","Philadelphia, PA","San Antonio, TX","San Diego, CA","Dallas, TX","Austin, TX","San Francisco, CA","Seattle, WA","Denver, CO","Boston, MA","Miami, FL","Atlanta, GA","Portland, OR","Nashville, TN","Minneapolis, MN"],
  "Canada": ["Toronto, ON","Vancouver, BC","Montreal, QC","Calgary, AB","Ottawa, ON","Edmonton, AB","Winnipeg, MB","Quebec City, QC","Halifax, NS"],
  "United Kingdom": ["London","Manchester","Birmingham","Edinburgh","Glasgow","Liverpool","Bristol","Leeds","Belfast","Cardiff"],
  "Ireland": ["Dublin","Cork","Galway","Limerick"],
  "Australia": ["Sydney","Melbourne","Brisbane","Perth","Adelaide","Canberra","Gold Coast","Hobart"],
  "New Zealand": ["Auckland","Wellington","Christchurch","Queenstown"],
  "Germany": ["Berlin","Munich","Hamburg","Frankfurt","Cologne","Stuttgart","Düsseldorf","Leipzig"],
  "France": ["Paris","Lyon","Marseille","Toulouse","Nice","Bordeaux","Strasbourg","Nantes"],
  "Spain": ["Madrid","Barcelona","Valencia","Seville","Bilbao","Málaga","Granada"],
  "Italy": ["Rome","Milan","Florence","Venice","Naples","Turin","Bologna"],
  "Portugal": ["Lisbon","Porto","Faro","Coimbra"],
  "Netherlands": ["Amsterdam","Rotterdam","The Hague","Utrecht","Eindhoven"],
  "Belgium": ["Brussels","Antwerp","Ghent","Bruges"],
  "Switzerland": ["Zurich","Geneva","Basel","Bern","Lausanne"],
  "Austria": ["Vienna","Salzburg","Innsbruck","Graz"],
  "Sweden": ["Stockholm","Gothenburg","Malmö"],
  "Norway": ["Oslo","Bergen","Trondheim"],
  "Denmark": ["Copenhagen","Aarhus","Odense"],
  "Finland": ["Helsinki","Tampere","Turku"],
  "Iceland": ["Reykjavik"],
  "Poland": ["Warsaw","Krakow","Wrocław","Gdańsk"],
  "Czech Republic": ["Prague","Brno"],
  "Greece": ["Athens","Thessaloniki","Heraklion"],
  "Turkey": ["Istanbul","Ankara","Izmir","Antalya"],
  "Russia": ["Moscow","Saint Petersburg","Novosibirsk"],
  "Ukraine": ["Kyiv","Lviv","Odesa"],
  "Japan": ["Tokyo","Osaka","Kyoto","Yokohama","Nagoya","Sapporo","Fukuoka"],
  "South Korea": ["Seoul","Busan","Incheon","Jeju"],
  "China": ["Beijing","Shanghai","Guangzhou","Shenzhen","Chengdu","Hong Kong"],
  "India": ["Mumbai","Delhi","Bengaluru","Hyderabad","Chennai","Kolkata","Pune"],
  "Singapore": ["Singapore"],
  "Thailand": ["Bangkok","Chiang Mai","Phuket"],
  "Vietnam": ["Hanoi","Ho Chi Minh City","Da Nang"],
  "Indonesia": ["Jakarta","Bali (Denpasar)","Surabaya"],
  "Malaysia": ["Kuala Lumpur","Penang","Johor Bahru"],
  "Philippines": ["Manila","Cebu City","Davao City"],
  "Mexico": ["Mexico City","Guadalajara","Monterrey","Cancún","Tijuana"],
  "Brazil": ["São Paulo","Rio de Janeiro","Brasília","Salvador","Belo Horizonte"],
  "Argentina": ["Buenos Aires","Córdoba","Mendoza"],
  "Chile": ["Santiago","Valparaíso"],
  "Colombia": ["Bogotá","Medellín","Cartagena"],
  "Peru": ["Lima","Cusco","Arequipa"],
  "South Africa": ["Cape Town","Johannesburg","Durban","Pretoria"],
  "Egypt": ["Cairo","Alexandria","Luxor"],
  "United Arab Emirates": ["Dubai","Abu Dhabi","Sharjah"],
  "Israel": ["Tel Aviv","Jerusalem","Haifa"],
  "Saudi Arabia": ["Riyadh","Jeddah","Mecca"],
  "Nigeria": ["Lagos","Abuja"],
  "Kenya": ["Nairobi","Mombasa"],
  "Morocco": ["Casablanca","Marrakech","Rabat"],
};
